name: Build SunamoDebugging

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoDebugging
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoDebugging/SunamoDebugging.csproj

    - name: Build
      run: dotnet build SunamoDebugging/SunamoDebugging.csproj --configuration Release --no-restore

  test:
    name: Test SunamoDebugging.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoDebugging.Tests/SunamoDebugging.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoDebugging.Tests/SunamoDebugging.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoDebugging.Tests/SunamoDebugging.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
